service: cafe-management

frameworkVersion: '3'

useDotenv: true

plugins:
  - serverless-esbuild
  - serverless-dotenv-plugin
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies
  - serverless-plugin-split-stacks

package:
  excludeDevDependencies: false
  individually: true

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: ${self:custom.region.${self:provider.stage}}
  # environment:
  #   TABLE_NAME: ${env:TABLE_NAME}

#  iam:
#    role:
#      statements:
#        - Effect: Allow
#          Action:
#            - 'dynamodb:*'
#          Resource: '*'

custom:
  region:
    dev: us-east-2
    prod: us-east-1
  esbuild:
    packager: 'yarn'
  splitStacks:
    perFunction: false
    perType: false
    perGroupFunction: true
    nestedStackCount: 10

functions:
  hello:
    handler: functions/hello.main
    events:
      - http:
          path: hello
          method: post
          cors: true